package org.nxy.bridge.ui.theme

import android.os.Build
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.dynamicDarkColorScheme
import androidx.compose.material3.dynamicLightColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.platform.LocalContext

val blueLightScheme = lightColorScheme(
    primary = bluePrimaryLight,
    onPrimary = blueOnPrimaryLight,
    primaryContainer = bluePrimaryContainerLight,
    onPrimaryContainer = blueOnPrimaryContainerLight,
    secondary = blueSecondaryLight,
    onSecondary = blueOnSecondaryLight,
    secondaryContainer = blueSecondaryContainerLight,
    onSecondaryContainer = blueOnSecondaryContainerLight,
    tertiary = blueTertiaryLight,
    onTertiary = blueOnTertiaryLight,
    tertiaryContainer = blueTertiaryContainerLight,
    onTertiaryContainer = blueOnTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = blueBackgroundLight,
    onBackground = blueOnBackgroundLight,
    surface = blueSurfaceLight,
    onSurface = blueOnSurfaceLight,
    surfaceVariant = blueSurfaceVariantLight,
    onSurfaceVariant = blueOnSurfaceVariantLight,
    outline = blueOutlineLight,
    outlineVariant = blueOutlineVariantLight,
    scrim = blueScrimLight,
    inverseSurface = blueInverseSurfaceLight,
    inverseOnSurface = blueInverseOnSurfaceLight,
    inversePrimary = blueInversePrimaryLight,
    surfaceDim = blueSurfaceDimLight,
    surfaceBright = blueSurfaceBrightLight,
    surfaceContainerLowest = blueSurfaceContainerLowestLight,
    surfaceContainerLow = blueSurfaceContainerLowLight,
    surfaceContainer = blueSurfaceContainerLight,
    surfaceContainerHigh = blueSurfaceContainerHighLight,
    surfaceContainerHighest = blueSurfaceContainerHighestLight,
)

val blueDarkScheme = darkColorScheme(
    primary = bluePrimaryDark,
    onPrimary = blueOnPrimaryDark,
    primaryContainer = bluePrimaryContainerDark,
    onPrimaryContainer = blueOnPrimaryContainerDark,
    secondary = blueSecondaryDark,
    onSecondary = blueOnSecondaryDark,
    secondaryContainer = blueSecondaryContainerDark,
    onSecondaryContainer = blueOnSecondaryContainerDark,
    tertiary = blueTertiaryDark,
    onTertiary = blueOnTertiaryDark,
    tertiaryContainer = blueTertiaryContainerDark,
    onTertiaryContainer = blueOnTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = blueBackgroundDark,
    onBackground = blueOnBackgroundDark,
    surface = blueSurfaceDark,
    onSurface = blueOnSurfaceDark,
    surfaceVariant = blueSurfaceVariantDark,
    onSurfaceVariant = blueOnSurfaceVariantDark,
    outline = blueOutlineDark,
    outlineVariant = blueOutlineVariantDark,
    scrim = blueScrimDark,
    inverseSurface = blueInverseSurfaceDark,
    inverseOnSurface = blueInverseOnSurfaceDark,
    inversePrimary = blueInversePrimaryDark,
    surfaceDim = blueSurfaceDimDark,
    surfaceBright = blueSurfaceBrightDark,
    surfaceContainerLowest = blueSurfaceContainerLowestDark,
    surfaceContainerLow = blueSurfaceContainerLowDark,
    surfaceContainer = blueSurfaceContainerDark,
    surfaceContainerHigh = blueSurfaceContainerHighDark,
    surfaceContainerHighest = blueSurfaceContainerHighestDark,
)

val blueMediumContrastLightColorScheme = lightColorScheme(
    primary = bluePrimaryLightMediumContrast,
    onPrimary = blueOnPrimaryLightMediumContrast,
    primaryContainer = bluePrimaryContainerLightMediumContrast,
    onPrimaryContainer = blueOnPrimaryContainerLightMediumContrast,
    secondary = blueSecondaryLightMediumContrast,
    onSecondary = blueOnSecondaryLightMediumContrast,
    secondaryContainer = blueSecondaryContainerLightMediumContrast,
    onSecondaryContainer = blueOnSecondaryContainerLightMediumContrast,
    tertiary = blueTertiaryLightMediumContrast,
    onTertiary = blueOnTertiaryLightMediumContrast,
    tertiaryContainer = blueTertiaryContainerLightMediumContrast,
    onTertiaryContainer = blueOnTertiaryContainerLightMediumContrast,
    error = errorLightMediumContrast,
    onError = onErrorLightMediumContrast,
    errorContainer = errorContainerLightMediumContrast,
    onErrorContainer = onErrorContainerLightMediumContrast,
    background = blueBackgroundLightMediumContrast,
    onBackground = blueOnBackgroundLightMediumContrast,
    surface = blueSurfaceLightMediumContrast,
    onSurface = blueOnSurfaceLightMediumContrast,
    surfaceVariant = blueSurfaceVariantLightMediumContrast,
    onSurfaceVariant = blueOnSurfaceVariantLightMediumContrast,
    outline = blueOutlineLightMediumContrast,
    outlineVariant = blueOutlineVariantLightMediumContrast,
    scrim = blueScrimLightMediumContrast,
    inverseSurface = blueInverseSurfaceLightMediumContrast,
    inverseOnSurface = blueInverseOnSurfaceLightMediumContrast,
    inversePrimary = blueInversePrimaryLightMediumContrast,
    surfaceDim = blueSurfaceDimLightMediumContrast,
    surfaceBright = blueSurfaceBrightLightMediumContrast,
    surfaceContainerLowest = blueSurfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = blueSurfaceContainerLowLightMediumContrast,
    surfaceContainer = blueSurfaceContainerLightMediumContrast,
    surfaceContainerHigh = blueSurfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = blueSurfaceContainerHighestLightMediumContrast,
)

val blueHighContrastLightColorScheme = lightColorScheme(
    primary = bluePrimaryLightHighContrast,
    onPrimary = blueOnPrimaryLightHighContrast,
    primaryContainer = bluePrimaryContainerLightHighContrast,
    onPrimaryContainer = blueOnPrimaryContainerLightHighContrast,
    secondary = blueSecondaryLightHighContrast,
    onSecondary = blueOnSecondaryLightHighContrast,
    secondaryContainer = blueSecondaryContainerLightHighContrast,
    onSecondaryContainer = blueOnSecondaryContainerLightHighContrast,
    tertiary = blueTertiaryLightHighContrast,
    onTertiary = blueOnTertiaryLightHighContrast,
    tertiaryContainer = blueTertiaryContainerLightHighContrast,
    onTertiaryContainer = blueOnTertiaryContainerLightHighContrast,
    error = errorLightHighContrast,
    onError = onErrorLightHighContrast,
    errorContainer = errorContainerLightHighContrast,
    onErrorContainer = onErrorContainerLightHighContrast,
    background = blueBackgroundLightHighContrast,
    onBackground = blueOnBackgroundLightHighContrast,
    surface = blueSurfaceLightHighContrast,
    onSurface = blueOnSurfaceLightHighContrast,
    surfaceVariant = blueSurfaceVariantLightHighContrast,
    onSurfaceVariant = blueOnSurfaceVariantLightHighContrast,
    outline = blueOutlineLightHighContrast,
    outlineVariant = blueOutlineVariantLightHighContrast,
    scrim = blueScrimLightHighContrast,
    inverseSurface = blueInverseSurfaceLightHighContrast,
    inverseOnSurface = blueInverseOnSurfaceLightHighContrast,
    inversePrimary = blueInversePrimaryLightHighContrast,
    surfaceDim = blueSurfaceDimLightHighContrast,
    surfaceBright = blueSurfaceBrightLightHighContrast,
    surfaceContainerLowest = blueSurfaceContainerLowestLightHighContrast,
    surfaceContainerLow = blueSurfaceContainerLowLightHighContrast,
    surfaceContainer = blueSurfaceContainerLightHighContrast,
    surfaceContainerHigh = blueSurfaceContainerHighLightHighContrast,
    surfaceContainerHighest = blueSurfaceContainerHighestLightHighContrast,
)

val blueMediumContrastDarkColorScheme = darkColorScheme(
    primary = bluePrimaryDarkMediumContrast,
    onPrimary = blueOnPrimaryDarkMediumContrast,
    primaryContainer = bluePrimaryContainerDarkMediumContrast,
    onPrimaryContainer = blueOnPrimaryContainerDarkMediumContrast,
    secondary = blueSecondaryDarkMediumContrast,
    onSecondary = blueOnSecondaryDarkMediumContrast,
    secondaryContainer = blueSecondaryContainerDarkMediumContrast,
    onSecondaryContainer = blueOnSecondaryContainerDarkMediumContrast,
    tertiary = blueTertiaryDarkMediumContrast,
    onTertiary = blueOnTertiaryDarkMediumContrast,
    tertiaryContainer = blueTertiaryContainerDarkMediumContrast,
    onTertiaryContainer = blueOnTertiaryContainerDarkMediumContrast,
    error = errorDarkMediumContrast,
    onError = onErrorDarkMediumContrast,
    errorContainer = errorContainerDarkMediumContrast,
    onErrorContainer = onErrorContainerDarkMediumContrast,
    background = blueBackgroundDarkMediumContrast,
    onBackground = blueOnBackgroundDarkMediumContrast,
    surface = blueSurfaceDarkMediumContrast,
    onSurface = blueOnSurfaceDarkMediumContrast,
    surfaceVariant = blueSurfaceVariantDarkMediumContrast,
    onSurfaceVariant = blueOnSurfaceVariantDarkMediumContrast,
    outline = blueOutlineDarkMediumContrast,
    outlineVariant = blueOutlineVariantDarkMediumContrast,
    scrim = blueScrimDarkMediumContrast,
    inverseSurface = blueInverseSurfaceDarkMediumContrast,
    inverseOnSurface = blueInverseOnSurfaceDarkMediumContrast,
    inversePrimary = blueInversePrimaryDarkMediumContrast,
    surfaceDim = blueSurfaceDimDarkMediumContrast,
    surfaceBright = blueSurfaceBrightDarkMediumContrast,
    surfaceContainerLowest = blueSurfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = blueSurfaceContainerLowDarkMediumContrast,
    surfaceContainer = blueSurfaceContainerDarkMediumContrast,
    surfaceContainerHigh = blueSurfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = blueSurfaceContainerHighestDarkMediumContrast,
)

val blueHighContrastDarkColorScheme = darkColorScheme(
    primary = bluePrimaryDarkHighContrast,
    onPrimary = blueOnPrimaryDarkHighContrast,
    primaryContainer = bluePrimaryContainerDarkHighContrast,
    onPrimaryContainer = blueOnPrimaryContainerDarkHighContrast,
    secondary = blueSecondaryDarkHighContrast,
    onSecondary = blueOnSecondaryDarkHighContrast,
    secondaryContainer = blueSecondaryContainerDarkHighContrast,
    onSecondaryContainer = blueOnSecondaryContainerDarkHighContrast,
    tertiary = blueTertiaryDarkHighContrast,
    onTertiary = blueOnTertiaryDarkHighContrast,
    tertiaryContainer = blueTertiaryContainerDarkHighContrast,
    onTertiaryContainer = blueOnTertiaryContainerDarkHighContrast,
    error = errorDarkHighContrast,
    onError = onErrorDarkHighContrast,
    errorContainer = errorContainerDarkHighContrast,
    onErrorContainer = onErrorContainerDarkHighContrast,
    background = blueBackgroundDarkHighContrast,
    onBackground = blueOnBackgroundDarkHighContrast,
    surface = blueSurfaceDarkHighContrast,
    onSurface = blueOnSurfaceDarkHighContrast,
    surfaceVariant = blueSurfaceVariantDarkHighContrast,
    onSurfaceVariant = blueOnSurfaceVariantDarkHighContrast,
    outline = blueOutlineDarkHighContrast,
    outlineVariant = blueOutlineVariantDarkHighContrast,
    scrim = blueScrimDarkHighContrast,
    inverseSurface = blueInverseSurfaceDarkHighContrast,
    inverseOnSurface = blueInverseOnSurfaceDarkHighContrast,
    inversePrimary = blueInversePrimaryDarkHighContrast,
    surfaceDim = blueSurfaceDimDarkHighContrast,
    surfaceBright = blueSurfaceBrightDarkHighContrast,
    surfaceContainerLowest = blueSurfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = blueSurfaceContainerLowDarkHighContrast,
    surfaceContainer = blueSurfaceContainerDarkHighContrast,
    surfaceContainerHigh = blueSurfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = blueSurfaceContainerHighestDarkHighContrast,
)

@Composable
fun BridgeTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    // 默认禁用动态颜色
    dynamicColor: Boolean = false,
    content: @Composable () -> Unit
) {
    val colorScheme = when {
        dynamicColor && Build.VERSION.SDK_INT >= Build.VERSION_CODES.S -> {
            val context = LocalContext.current
            if (darkTheme) dynamicDarkColorScheme(context) else dynamicLightColorScheme(context)
        }

        darkTheme -> blueDarkScheme
        else -> blueLightScheme
    }

    MaterialTheme(
        colorScheme = colorScheme,
        typography = Typography,
        content = content
    )
}